### ISSUE TITLE
Virtual scrolling with external data provider

### ISSUE THREAD

**Issue by KorsG** [jamesdruhan/vue-jd-table#15]
First off, great work with this component and all the advanced features out-of-the-box 👍 

The "only" thing I am missing is virtual scrolling support with an external data provider, and I can see it may? have been supported at one point, but removed via this commit:
[https://github.com/jamesdruhan/vue-jd-table/commit/69b3a93911734dadf760edf1cf007ba3d0cad0ff](url)

I am working on a project where it is required and I might consided making a fork of this project and try to implement it, but I thought I would ask you first if you would reconsider implementing it, or otherwise give some tips/pointers on how it should be done? 🙂

**Comment by jamesdruhan** [comment]
@KorsG, virtual scrolling with external data support exists with JD-Table -- it is just implemented in a different way. I use virtual scrolling with external data on a number of my projects and it works great. It does require a bit more work on your part though.

Basically, any action of the table that manipulates the view of data will emit an event that you need to manage manually. For example, sorting, searching, filtering, paging, etc. All those actions trigger events that allows you to manage the external manipulation. This approach was taken because there are way too many external data sources to create simplified plugins for.

- Check out the data provider setting [here](https://github.com/jamesdruhan/vue-jd-table/blob/master/docs/Options.md#dataprovider). Use "1" for external data.

- Check out the Events that are triggered [here](https://github.com/jamesdruhan/vue-jd-table/blob/master/docs/Events.md#JD-Table-Events-to-Your-App). Scroll down and see all the events you need to plan for external data.

**Comment by jamesdruhan** [comment]
Had to correct my last post. I completely forgot I removed that option completely for virtual scrolling (sorry!).

To answer your question, if you were to implement virtual scrolling you will need to trigger new emit events when the virtual scroll triggers a next/previous request for data. It should work great but I haven't had a chance to try implementing it. This is all done in the rendering function.

**Comment by KorsG** [comment]
Thanks for responding so quickly @jamesdruhan 👍 (and sorry for my late response).

I went with another solution that supports it out-of-the-box, but I will definitely keep this solution in mind for other projects where it might fit better.
