### ISSUE TITLE
Append row data rather than always replace

### ISSUE THREAD

**Issue by mwgamble** [jamesdruhan/vue-jd-table#8]
It would be great if there was a way to append data to the table without having it refresh the entire table, so that you don't have to lose your scroll position while adding new rows.

Is there any way that this would be possible? I have a use case where I have sorting turned completely off, for example.

**Comment by jamesdruhan** [comment]
In it's current implementation JD-Table does not have this feature.

@mwgamble this is a great idea. I've actually never had a use case myself for this or I would have definitely implemented this capability. There is a lot that happens when data is refreshed, especially if the virtual scroll render engine is used. Something as simple as manipulating a single cell that changes that row height could potentially cause issues with scroll heights if a full render is not performed.

That being said, I like the idea. I'll add it to my 'todo' list for future enhancements.
